### ISSUE TITLE
话题列表默认返回的是热门，什么参数可以返回最新帖？

### ISSUE THREAD

**Issue by EasonJolter** [viko16/ZuiYouApi#1]
POST http://share.izuiyou.com/api/topic/details
参数：
{"h_av":"3.0","h_dt":9,"h_nt":9,"h_ch":"web_app","ua":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Mobile Safari/537.36","tid":431788}

**Comment by viko16** [comment]
这个仓库的内容是我在 2015 年分析的，在 2016 年之后已经没有再继续研究下去了。

因此你的问题我目前无法回答，非常抱歉 : (

**Comment by EasonJolter** [comment]
现在的请求参数都加密，看不到具体的key value了
